travis:
  secure:
    BINSTAR_TOKEN: bvl9aO3hVYH1CXQjdJ6YoXKTi7epn93FnFZFSHJ1JsBwV1d/Y/3BSg/ylT6DsauJln0miWQXaZ4EtNIZDMONleGD6DJD+j6q2CqYdsn9YzT3JBCIRRibRvlUOnK+AiBZWO0fgr4u45Om22AYS/ZQjYl+X71tNbW/ZOwqpRUpq+aREKCezFwe1WhEK21eHlWqBTNbTWK5V7rkEOkpSxT83DdqQC34qPoYHBjED2ai0yOeJ77oY8bk33EFX9DXmNuVCsp2nJOaS0vYWbbOUvAL7NqI32wG6JGRksKfdonR/yrtuMDLJlB6B0d6kh/tp4LLMQ6E4zA74fxi2rfLAwlZIvYRHDfwzYGT5sdkTnMg97kcC70m2cKRmxNy1qEAhmSIW/mk3DajRzlcxfsKF7O3rjlqn/0PF5TMkeNBCy4wh12pVd9b+zCuoewWXquW55OUtxGDKO3HTxOSvBpL2hmExpbLxq5vX9du2GAj53mLI8JMUuKlThhPah+oJguU25JrhDWFcKXTz/fe2slKxCJnWMBO7+ezm857zhejXf3mtqxSFJqu6hUpHqkOx3SBaZWBBkfG5iZd/cxv5J1Vu+e3jx1iZCnxlrbcX4V1u2DPA4OOUuXHdoA1SSFXLvQQT9GQwgK+OFmMIHP/tgLarxBDiwx4sga7W1FbPsXdwa6XJcI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
